/* tslint:disable */
/* eslint-disable */
/**
 * Zod Fastify Test Server
 * API for Zod Fastify Test Server
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TodoItem,
    TodoItemFromJSON,
    TodoItemFromJSONTyped,
    TodoItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface TodoItems
 */
export interface TodoItems extends Array<TodoItem> {
}

export function TodoItemsFromJSON(json: any): TodoItems {
    return TodoItemsFromJSONTyped(json, false);
}

export function TodoItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItems {
    return json;
}

export function TodoItemsToJSON(value?: TodoItems | null): any {
    return value;
}


