/* tslint:disable */
/* eslint-disable */
/**
 * Zod Fastify Test Server
 * API for Zod Fastify Test Server
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoItem
 */
export interface TodoItem {
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    label: string;
    /**
     * 
     * @type {Date}
     * @memberof TodoItem
     */
    due_date?: Date;
    /**
     * 
     * @type {string}
     * @memberof TodoItem
     */
    state: TodoItemStateEnum;
}

/**
* @export
* @enum {string}
*/
export enum TodoItemStateEnum {
    Todo = 'todo',
    InProgress = 'in progress',
    Done = 'done'
}

export function TodoItemFromJSON(json: any): TodoItem {
    return TodoItemFromJSONTyped(json, false);
}

export function TodoItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'due_date': !exists(json, 'dueDate') ? undefined : (new Date(json['dueDate'])),
        'state': json['state'],
    };
}

export function TodoItemToJSON(value?: TodoItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
        'dueDate': value.due_date === undefined ? undefined : (value.due_date.toISOString()),
        'state': value.state,
    };
}


